{% set name = "xsarsea" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsarsea-{{ version }}.tar.gz
  sha256: 8067277e77a3fc891827c76d3eac4e0d2762a3d6e862a0eb3fca8f41e449f90b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - setuptools-scm
    - pip
  run:
    - python
    - numpy
    - xarray
    - opencv
    - importlib-resources
    - fsspec
    - aiohttp
    - numba
    - scipy
    - pyyaml
    - typer
    - netcdf4
    - matplotlib-base
    - xrft

test:
  imports:
    - xsarsea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/umr-lops/xsarsea
  summary: cmod, detrend, and others sar processing tools over ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
