{% set name = "xsarsea" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsarsea-{{ version }}.tar.gz
  sha256: 454e07b312d79f86d2afba05c7cd95cf26e7a406dd852d2c177be3d30db6607f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools-scm
    - pip
  run:
    - python
    - numpy
    - xarray
    - opencv
    - importlib-resources
    - fsspec
    - aiohttp
    - numba
    - scipy
    - pyyaml
    - typer
    - netcdf4
    - matplotlib-base
    - xrft

test:
  imports:
    - xsarsea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/umr-lops/xsarsea
  summary: cmod, detrend, and others sar processing tools over ocean
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
